export const CATEGORIES = [
  { id: 'masalas', name: 'Masalas & spices', emoji: '🌶️', hue: '#e8bd61', blurb: 'Whole spices, powders and the blends every curry starts with.' },
  { id: 'rice', name: 'Rice & grains', emoji: '🍚', hue: '#d7d2b5', blurb: 'Aged basmati, sona masoori, poha and grains in every size.' },
  { id: 'flour', name: 'Atta & flours', emoji: '🫓', hue: '#e3cfa8', blurb: 'Chakki atta, besan, maida and sooji for rotis and more.' },
  { id: 'dals', name: 'Dals & lentils', emoji: '🫘', hue: '#dfae7c', blurb: 'Toor, moong, chana, rajma — the heart of the pantry.' },
  { id: 'snacks', name: 'Snacks & sweets', emoji: '🍬', hue: '#d86b3e', blurb: 'Namkeen, biscuits, instant mixes and celebratory mithai.' },
  { id: 'pantry', name: 'Sauces, pickles & pantry', emoji: '🫙', hue: '#c98a4b', blurb: 'Pickles, pastes, ghee, oils and chutneys.' },
  { id: 'frozen', name: 'Frozen & dairy', emoji: '🧊', hue: '#c8ded9', blurb: 'Paneer, parathas, samosas, butter and dahi.' },
  { id: 'drinks', name: 'Tea & drinks', emoji: '🫖', hue: '#eed8c0', blurb: 'Chai, malt drinks and refreshing favourites from home.' },
  { id: 'fresh', name: 'Fresh produce', emoji: '🥬', hue: '#a9b392', blurb: 'Okra, curry leaves, herbs and seasonal fruit each week.' },
];

export const PRODUCTS = [
  // Masalas & spices
  { id: 'shan-butter', cat: 'masalas', brand: 'Shan', name: 'Butter Chicken Masala', size: '50 g', price: 2.5 },
  { id: 'shan-korma', cat: 'masalas', brand: 'Shan', name: 'Chicken White Korma Mix', size: '40 g', price: 2.5 },
  { id: 'shan-tikka', cat: 'masalas', brand: 'Shan', name: 'Chicken Tikka Mix', size: '50 g', price: 2.5 },
  { id: 'shan-chaat', cat: 'masalas', brand: 'Shan', name: 'Chaat Masala', size: '100 g', price: 3.5 },
  { id: 'mdh-butter-chicken', cat: 'masalas', brand: 'MDH', name: 'Butter Chicken Masala', size: '100 g', price: 4.5 },
  { id: 'mdh-bombay-biryani', cat: 'masalas', brand: 'MDH', name: 'Bombay Biryani Masala', size: '100 g', price: 4.5 },
  { id: 'mdh-garam', cat: 'masalas', brand: 'MDH', name: 'Garam Masala', size: '100 g', price: 4.5 },
  { id: 'mdh-kitchen-king', cat: 'masalas', brand: 'MDH', name: 'Kitchen King Masala', size: '100 g', price: 4.5 },
  { id: 'mdh-chana', cat: 'masalas', brand: 'MDH', name: 'Chana Masala', size: '100 g', price: 4.5 },
  { id: 'mdh-deggi', cat: 'masalas', brand: 'MDH', name: 'Deggi Mirch', size: '100 g', price: 4.5 },
  { id: 'mdh-chunky-chat', cat: 'masalas', brand: 'MDH', name: 'Chunky Chat Masala', size: '100 g', price: 4.5 },
  { id: 'everest-chicken', cat: 'masalas', brand: 'Everest', name: 'Chicken Masala', size: '100 g', price: 4 },
  { id: 'everest-shahi-paneer', cat: 'masalas', brand: 'Everest', name: 'Shahi Paneer Masala', size: '100 g', price: 4 },
  { id: 'everest-methi', cat: 'masalas', brand: 'Everest', name: 'Kasuri Methi', size: '100 g', price: 3 },
  { id: 'eastern-biryani', cat: 'masalas', brand: 'Eastern', name: 'Biryani Masala', size: '100 g', price: 3.5 },
  { id: 'dt-garam-whole', cat: 'masalas', brand: 'DT', name: 'Whole Garam Masala', size: '200 g', price: 6.5 },
  { id: 'shudh-turmeric', cat: 'masalas', brand: 'Shudh', name: 'Turmeric Powder', size: '250 g', price: 4.5 },
  { id: 'shudh-chilli', cat: 'masalas', brand: 'Shudh', name: 'Red Chilli Powder', size: '250 g', price: 5 },
  { id: 'shudh-coriander-pwd', cat: 'masalas', brand: 'Shudh', name: 'Coriander Powder', size: '250 g', price: 4.5 },
  { id: 'shudh-cumin', cat: 'masalas', brand: 'Shudh', name: 'Cumin Seeds (Jeera)', size: '250 g', price: 5 },
  { id: 'shudh-cardamom', cat: 'masalas', brand: 'Shudh', name: 'Green Cardamom', size: '50 g', price: 6.5 },
  { id: 'shudh-cinnamon', cat: 'masalas', brand: 'Shudh', name: 'Cinnamon Sticks', size: '100 g', price: 3.5 },

  // Rice & grains
  { id: 'daawat-trad-5', cat: 'rice', brand: 'Daawat', name: 'Traditional Basmati Rice', size: '5 kg', price: 32 },
  { id: 'daawat-select-5', cat: 'rice', brand: 'Daawat', name: 'Select Basmati Rice', size: '5 kg', price: 28 },
  { id: 'daawat-everyday-5', cat: 'rice', brand: 'Daawat', name: 'Everyday Basmati Rice', size: '5 kg', price: 25 },
  { id: 'fortune-basmati-5', cat: 'rice', brand: 'Fortune', name: 'Classic Basmati Rice', size: '5 kg', price: 26 },
  { id: 'ck-sona-masoori', cat: 'rice', brand: 'CK', name: 'Sona Masoori Rice', size: '5 kg', price: 24 },
  { id: 'indya-sona-masoori', cat: 'rice', brand: 'Indya', name: 'Sona Masoori Rice', size: '5 kg', price: 23 },
  { id: 'dt-poha-thick', cat: 'rice', brand: 'DT', name: 'Thick Poha', size: '1 kg', price: 5.5 },
  { id: 'dt-poha-thin', cat: 'rice', brand: 'DT', name: 'Thin Poha', size: '1 kg', price: 5.5 },

  // Atta & flours
  { id: 'aashirvaad-10', cat: 'flour', brand: 'Aashirvaad', name: 'Whole Wheat Atta', size: '10 kg', price: 32 },
  { id: 'aashirvaad-multigrain-5', cat: 'flour', brand: 'Aashirvaad', name: 'Multigrain Atta', size: '5 kg', price: 20 },
  { id: 'aus-punjab-5', cat: 'flour', brand: 'Aus Punjab', name: 'Chakki Atta', size: '5 kg', price: 17 },
  { id: 'aus-punjab-10', cat: 'flour', brand: 'Aus Punjab', name: 'Chakki Atta', size: '10 kg', price: 30 },
  { id: 'shudh-atta-10', cat: 'flour', brand: 'Shudh', name: 'Chakki Atta', size: '10 kg', price: 28 },
  { id: 'pattu-besan', cat: 'flour', brand: 'Pattu', name: 'Besan Fine (Gram Flour)', size: '800 g', price: 6 },
  { id: 'pattu-rice-flour', cat: 'flour', brand: 'Pattu', name: 'Rice Flour', size: '1 kg', price: 4.5 },
  { id: 'pattu-maida', cat: 'flour', brand: 'Pattu', name: 'Maida (Plain Flour)', size: '1 kg', price: 3.5 },
  { id: 'pattu-sooji', cat: 'flour', brand: 'Pattu', name: 'Sooji Coarse (Semolina)', size: '1 kg', price: 4.5 },

  // Dals & lentils
  { id: 'pattu-toor-1', cat: 'dals', brand: 'Pattu', name: 'Toor Dal', size: '1 kg', price: 7.5 },
  { id: 'pattu-toor-2', cat: 'dals', brand: 'Pattu', name: 'Toor Dal', size: '2 kg', price: 14 },
  { id: 'indya-moong', cat: 'dals', brand: 'Indya', name: 'Moong Dal', size: '1 kg', price: 6.5 },
  { id: 'pattu-chana-dal', cat: 'dals', brand: 'Pattu', name: 'Chana Dal', size: '1 kg', price: 5.5 },
  { id: 'pattu-urad', cat: 'dals', brand: 'Pattu', name: 'Urad Dal Gota', size: '1 kg', price: 8 },
  { id: 'indya-masoor', cat: 'dals', brand: 'Indya', name: 'Masoor Dal (Red Lentils)', size: '1 kg', price: 5.5 },
  { id: 'indya-rajma', cat: 'dals', brand: 'Indya', name: 'Rajma (Red Kidney Beans)', size: '1 kg', price: 6.5 },
  { id: 'indya-kabuli', cat: 'dals', brand: 'Indya', name: 'Kabuli Chickpeas', size: '2 kg', price: 11 },

  // Snacks & sweets
  { id: 'balaji-classic-sev', cat: 'snacks', brand: 'Balaji', name: 'Classic Sev', size: '400 g', price: 5.5 },
  { id: 'balaji-aloo-sev', cat: 'snacks', brand: 'Balaji', name: 'Aloo Sev', size: '400 g', price: 5.5 },
  { id: 'bikano-aloo-bhujia', cat: 'snacks', brand: 'Bikano', name: 'Aloo Bhujia', size: '1 kg', price: 9.5 },
  { id: 'bikano-bhujia', cat: 'snacks', brand: 'Bikano', name: 'Bikaneri Bhujia', size: '1 kg', price: 9.5 },
  { id: 'bambino-gulab-jamun', cat: 'snacks', brand: 'Bambino', name: 'Gulab Jamun Mix', size: '500 g', price: 7.5 },
  { id: 'bambino-soan-papdi', cat: 'snacks', brand: 'Bambino', name: 'Soan Papdi', size: '250 g', price: 5 },
  { id: 'parle-g', cat: 'snacks', brand: 'Parle', name: 'Parle-G Biscuits (family pack)', size: '752 g', price: 4.5 },
  { id: 'britannia-bourbon', cat: 'snacks', brand: 'Britannia', name: 'Bourbon Cream Biscuits', size: '390 g', price: 4 },
  { id: 'britannia-cake-rusk', cat: 'snacks', brand: 'Britannia', name: 'Cake Rusk', size: '560 g', price: 7 },
  { id: 'maggi-noodles', cat: 'snacks', brand: 'Maggi', name: 'Masala Noodles (8 pack)', size: '560 g', price: 6.5 },
  { id: 'kurkure', cat: 'snacks', brand: 'Kurkure', name: 'Masala Munch', size: '75 g', price: 2.5 },
  { id: 'gits-dosa', cat: 'snacks', brand: 'Gits', name: 'Dosa Mix', size: '500 g', price: 6 },
  { id: 'gits-jalebi', cat: 'snacks', brand: 'Gits', name: 'Jalebi Mix', size: '100 g', price: 3.5 },
  { id: 'mtr-rava-idli', cat: 'snacks', brand: 'MTR', name: 'Rava Idli Mix', size: '500 g', price: 6 },

  // Sauces, pickles & pantry
  { id: 'eastern-mango-pickle', cat: 'pantry', brand: 'Eastern', name: 'Mango Pickle', size: '400 g', price: 5.5 },
  { id: 'eastern-lime-pickle', cat: 'pantry', brand: 'Eastern', name: 'Lime Pickle', size: '400 g', price: 5.5 },
  { id: 'kt-gg-paste', cat: 'pantry', brand: 'KT', name: 'Ginger Garlic Paste', size: '350 g', price: 4 },
  { id: 'pattu-tamarind', cat: 'pantry', brand: 'Pattu', name: 'Tamarind Block', size: '500 g', price: 4.5 },
  { id: 'amul-ghee-500', cat: 'pantry', brand: 'Amul', name: 'Pure Cow Ghee', size: '500 ml', price: 12 },
  { id: 'amul-ghee-1l', cat: 'pantry', brand: 'Amul', name: 'Pure Cow Ghee', size: '1 L', price: 19 },
  { id: 'indya-mustard-oil', cat: 'pantry', brand: 'Indya', name: 'Mustard Oil', size: '1 L', price: 9 },
  { id: 'maggi-coconut-powder', cat: 'pantry', brand: 'Maggi', name: 'Coconut Milk Powder', size: '1 kg', price: 16 },
  { id: 'lijjat-papad', cat: 'pantry', brand: 'Lijjat', name: 'Plain Papad', size: '200 g', price: 3.5 },
  { id: 'lijjat-papad-cumin', cat: 'pantry', brand: 'Lijjat', name: 'Cumin Papad', size: '200 g', price: 3.5 },
  { id: 'sabrini-tamarind-chutney', cat: 'pantry', brand: 'Sabrini', name: 'Date & Tamarind Chutney', size: '360 g', price: 5 },
  { id: 'pattu-mint-chutney', cat: 'pantry', brand: 'Pattu', name: 'Mint Chutney', size: '280 g', price: 4.5 },
  { id: 'cashews-500', cat: 'pantry', brand: 'Pantry', name: 'Whole Cashew Nuts', size: '500 g', price: 11 },

  // Frozen & dairy
  { id: 'deep-garlic-naan-4', cat: 'frozen', brand: 'Deep', name: 'Garlic Naan (4 pc)', size: '400 g', price: 6 },
  { id: 'deep-garlic-naan-12', cat: 'frozen', brand: 'Deep', name: 'Garlic Naan (12 pc)', size: '1.2 kg', price: 14 },
  { id: 'deep-aloo-paratha', cat: 'frozen', brand: 'Deep', name: 'Aloo Paratha (4 pc)', size: '440 g', price: 6.5 },
  { id: 'deep-paneer-paratha', cat: 'frozen', brand: 'Deep', name: 'Paneer Paratha (4 pc)', size: '440 g', price: 7 },
  { id: 'deep-samosas', cat: 'frozen', brand: 'Deep', name: 'Cocktail Samosas (50 pc)', size: '1.5 kg', price: 16 },
  { id: 'deep-bhindi-cut', cat: 'frozen', brand: 'Deep', name: 'Frozen Bhindi Cut', size: '340 g', price: 4.5 },
  { id: 'deep-mango-pulp', cat: 'frozen', brand: 'Deep', name: 'Alphonso Mango Pulp', size: '850 g', price: 6.5 },
  { id: 'baps-paneer', cat: 'frozen', brand: 'BAPS', name: 'Frozen Paneer (25 pc)', size: '450 g', price: 8.5 },
  { id: 'amul-butter', cat: 'frozen', brand: 'Amul', name: 'Butter', size: '500 g', price: 8.5 },
  { id: 'fresh-dahi', cat: 'frozen', brand: 'Fresh', name: 'Set Yoghurt (Dahi)', size: '1 kg tub', price: 6.5 },

  // Tea & drinks
  { id: 'wagh-bakri-1kg', cat: 'drinks', brand: 'Wagh Bakri', name: 'Premium Tea', size: '1 kg', price: 16 },
  { id: 'wagh-bakri-masala', cat: 'drinks', brand: 'Wagh Bakri', name: 'Masala Chai', size: '250 g', price: 6.5 },
  { id: 'red-label-900', cat: 'drinks', brand: 'Brooke Bond', name: 'Red Label Tea', size: '900 g', price: 14 },
  { id: 'rooh-afza', cat: 'drinks', brand: 'Hamdard', name: 'Rooh Afza', size: '750 ml', price: 8 },
  { id: 'thums-up', cat: 'drinks', brand: 'Thums Up', name: 'Soft Drink', size: '300 ml', price: 2.5 },
  { id: 'frooti-2l', cat: 'drinks', brand: 'Frooti', name: 'Mango Drink', size: '2 L', price: 6 },
  { id: 'appy-fizz', cat: 'drinks', brand: 'Parle', name: 'Appy Fizz Sparkling Apple', size: '600 ml', price: 3 },

  // Fresh produce
  { id: 'okra', cat: 'fresh', brand: 'Fresh', name: 'Okra (Bhindi)', size: '500 g', price: 6 },
  { id: 'coriander-bunch', cat: 'fresh', brand: 'Fresh', name: 'Coriander Leaves', size: 'bunch', price: 2.5 },
  { id: 'curry-leaves', cat: 'fresh', brand: 'Fresh', name: 'Curry Leaves', size: 'pack', price: 3 },
  { id: 'mint-bunch', cat: 'fresh', brand: 'Fresh', name: 'Mint Leaves', size: 'bunch', price: 2.5 },
  { id: 'green-chillies', cat: 'fresh', brand: 'Fresh', name: 'Green Chillies', size: '250 g', price: 4 },
  { id: 'ginger', cat: 'fresh', brand: 'Fresh', name: 'Ginger', size: 'per kg', price: 14 },
  { id: 'garlic', cat: 'fresh', brand: 'Fresh', name: 'Garlic', size: 'per kg', price: 12 },
  { id: 'baby-eggplant', cat: 'fresh', brand: 'Fresh', name: 'Eggplant (Purple)', size: '500 g', price: 4.5 },
  { id: 'coconut-fresh', cat: 'fresh', brand: 'Fresh', name: 'Whole Coconut', size: 'each', price: 3.5 },
  { id: 'beetroot', cat: 'fresh', brand: 'Fresh', name: 'Beetroot', size: 'per kg', price: 5 },
  { id: 'banana', cat: 'fresh', brand: 'Fresh', name: 'Bananas', size: 'per kg', price: 4.5 },
  { id: 'onions-2kg', cat: 'fresh', brand: 'Fresh', name: 'Brown Onions', size: '2 kg bag', price: 5 },
  { id: 'tomatoes', cat: 'fresh', brand: 'Fresh', name: 'Tomatoes', size: 'per kg', price: 6 },
  { id: 'lemons', cat: 'fresh', brand: 'Fresh', name: 'Lemons', size: 'each', price: 1.2 },
];

export const RECIPES = [
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    emoji: '🍛',
    tagline: 'The one everyone asks for',
    time: '50 min',
    serves: 4,
    difficulty: 'Easy',
    intro: 'Silky, gently spiced and family-friendly — butter chicken is the perfect first Indian dish to cook at home. Everything you need for the sauce is on our shelves.',
    ingredients: [
      { label: '800 g chicken thigh fillets', pantry: true },
      { label: '300 ml cream & 400 g tomato passata', pantry: true },
      { label: 'Butter chicken spice mix', products: ['shan-butter', 'mdh-butter-chicken'] },
      { label: 'Ghee or butter', products: ['amul-ghee-500', 'amul-butter'] },
      { label: 'Ginger garlic paste', products: ['kt-gg-paste', 'ginger', 'garlic'] },
      { label: 'Garam masala (to finish)', products: ['mdh-garam', 'dt-garam-whole'] },
      { label: 'Kasuri methi — the secret touch', products: ['everest-methi'] },
      { label: 'Deggi mirch for colour, not heat', products: ['mdh-deggi'] },
      { label: 'Basmati rice, to serve', products: ['daawat-everyday-5', 'daawat-trad-5', 'fortune-basmati-5'] },
      { label: 'Fresh coriander, to garnish', products: ['coriander-bunch'] },
    ],
    steps: [
      'Marinate the chicken in half the spice mix with a spoon of yoghurt for 20 minutes (or overnight).',
      'Sear the chicken in a hot pan with a little ghee until golden. Set aside.',
      'In the same pan, melt 2 tbsp ghee and cook the ginger garlic paste for a minute until fragrant.',
      'Add the passata and remaining spice mix. Simmer 10 minutes until rich and glossy.',
      'Stir in the cream, return the chicken and simmer gently for 10 minutes.',
      'Finish with a pinch of garam masala and crushed kasuri methi. Garnish with coriander and serve with fluffy basmati rice.',
    ],
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken Biryani',
    emoji: '🍚',
    tagline: 'A celebration in a pot',
    time: '1 hr 15 min',
    serves: 6,
    difficulty: 'Medium',
    intro: 'Layers of fragrant rice, spiced chicken and fried onions. It looks impressive — and with a good biryani masala it is much easier than you think.',
    ingredients: [
      { label: '1 kg chicken pieces, bone-in', pantry: true },
      { label: 'Biryani masala', products: ['mdh-bombay-biryani', 'eastern-biryani'] },
      { label: 'Aged basmati rice (2½ cups)', products: ['daawat-trad-5', 'daawat-select-5', 'fortune-basmati-5'] },
      { label: 'Yoghurt for the marinade', products: ['fresh-dahi'] },
      { label: 'Ghee', products: ['amul-ghee-500', 'amul-ghee-1l'] },
      { label: 'Onions, thinly sliced & fried golden', products: ['onions-2kg'] },
      { label: 'Fresh mint & coriander', products: ['mint-bunch', 'coriander-bunch'] },
      { label: 'Whole spices — cardamom & cinnamon', products: ['shudh-cardamom', 'shudh-cinnamon', 'dt-garam-whole'] },
      { label: 'Green chillies', products: ['green-chillies'] },
    ],
    steps: [
      'Marinate the chicken in yoghurt, biryani masala and half the fried onions for at least 30 minutes.',
      'Soak the basmati rice for 30 minutes, then parboil with the whole spices until 70% cooked. Drain.',
      'Cook the marinated chicken in a heavy pot for 10 minutes until the masala thickens.',
      'Layer the rice over the chicken. Scatter with mint, coriander, fried onions and a drizzle of ghee.',
      'Cover tightly and steam on the lowest heat (dum) for 25 minutes. Do not peek!',
      'Rest 10 minutes, then gently fluff from the bottom so every serve gets rice and chicken. Serve with raita.',
    ],
  },
  {
    id: 'lamb-rogan-josh',
    name: 'Lamb Rogan Josh',
    emoji: '🍖',
    tagline: 'Deep, rich & perfect for Ballarat winters',
    time: '1 hr 45 min',
    serves: 4,
    difficulty: 'Medium',
    intro: 'A slow-cooked Kashmiri classic. Deggi mirch gives its famous red colour with gentle warmth — brilliant with Aussie lamb.',
    ingredients: [
      { label: '1 kg lamb shoulder, cubed', pantry: true },
      { label: '2 onions & 2 tomatoes', products: ['onions-2kg', 'tomatoes'] },
      { label: 'Deggi mirch (Kashmiri-style chilli)', products: ['mdh-deggi'] },
      { label: 'Garam masala', products: ['mdh-garam', 'dt-garam-whole'] },
      { label: 'Coriander powder', products: ['shudh-coriander-pwd'] },
      { label: 'Ginger garlic paste', products: ['kt-gg-paste'] },
      { label: 'Whole spices — cardamom & cinnamon', products: ['shudh-cardamom', 'shudh-cinnamon'] },
      { label: 'Yoghurt', products: ['fresh-dahi'] },
      { label: 'Ghee or mustard oil', products: ['amul-ghee-500', 'indya-mustard-oil'] },
      { label: 'Basmati rice, to serve', products: ['daawat-trad-5', 'daawat-everyday-5'] },
    ],
    steps: [
      'Brown the lamb in ghee in batches and set aside.',
      'Cook sliced onions until deep golden, then add ginger garlic paste and the whole spices.',
      'Add deggi mirch, coriander powder and chopped tomatoes. Cook until the oil separates.',
      'Whisk in the yoghurt a spoon at a time, then return the lamb with a cup of water.',
      'Cover and simmer gently for 1¼ hours until the lamb is meltingly tender.',
      'Finish with garam masala and serve with basmati rice or hot parathas.',
    ],
  },
  {
    id: 'chicken-korma',
    name: 'Chicken Korma',
    emoji: '🥥',
    tagline: 'Mild, creamy & kid-approved',
    time: '45 min',
    serves: 4,
    difficulty: 'Easy',
    intro: 'The gentlest curry of them all — creamy, nutty and fragrant. If you are cooking for spice-shy eaters, start here.',
    ingredients: [
      { label: '700 g chicken thigh fillets', pantry: true },
      { label: '1 onion, finely sliced', products: ['onions-2kg'] },
      { label: 'Korma spice mix', products: ['shan-korma'] },
      { label: 'Coconut milk powder', products: ['maggi-coconut-powder'] },
      { label: 'Cashews (blended for creaminess)', products: ['cashews-500'] },
      { label: 'Ghee', products: ['amul-ghee-500'] },
      { label: 'Ginger garlic paste', products: ['kt-gg-paste'] },
      { label: 'Basmati rice, to serve', products: ['daawat-everyday-5', 'daawat-select-5'] },
      { label: 'Fresh coriander, to garnish', products: ['coriander-bunch'] },
    ],
    steps: [
      'Soak the cashews in hot water for 10 minutes, then blend into a smooth paste.',
      'Cook the onion in ghee until soft and golden, then add the ginger garlic paste.',
      'Stir in the korma mix and cook for a minute until fragrant.',
      'Add the chicken and seal on all sides, coating it in the spices.',
      'Whisk the coconut milk powder into 300 ml warm water, pour in with the cashew paste and simmer gently for 20 minutes.',
      'Garnish with coriander and serve over basmati rice with warm naan.',
    ],
  },
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    emoji: '🫘',
    tagline: 'Vegetarian comfort in a bowl',
    time: '40 min',
    serves: 4,
    difficulty: 'Easy',
    intro: 'The everyday soul food of India — soft golden lentils finished with a sizzling spiced ghee "tadka". Cheap, healthy and completely delicious.',
    ingredients: [
      { label: '1 onion & 2 tomatoes, chopped', products: ['onions-2kg', 'tomatoes'] },
      { label: 'Toor dal (1½ cups)', products: ['pattu-toor-1', 'indya-moong'] },
      { label: 'Turmeric powder', products: ['shudh-turmeric'] },
      { label: 'Cumin seeds', products: ['shudh-cumin'] },
      { label: 'Ghee for the tadka', products: ['amul-ghee-500'] },
      { label: 'Fresh garlic, sliced', products: ['garlic'] },
      { label: 'Green chillies', products: ['green-chillies'] },
      { label: 'Curry leaves', products: ['curry-leaves'] },
      { label: 'Fresh coriander, to garnish', products: ['coriander-bunch'] },
      { label: 'Rice or rotis, to serve', products: ['ck-sona-masoori', 'aus-punjab-5'] },
    ],
    steps: [
      'Rinse the dal, then simmer with turmeric, salt and 4 cups of water for 25 minutes until soft.',
      'Meanwhile cook the onion and tomatoes in a little ghee until jammy, and stir into the dal.',
      'Mash the dal lightly for a creamy texture, adding water to your liking.',
      'Make the tadka: heat ghee until shimmering, add cumin seeds, garlic, chillies and curry leaves. Sizzle 30 seconds.',
      'Pour the sizzling tadka over the dal at the table — the aroma is the best part.',
      'Top with coriander and serve with steamed rice or hot rotis.',
    ],
  },
  {
    id: 'garlic-naan',
    name: 'Garlic Naan',
    emoji: '🫓',
    tagline: 'The essential curry companion',
    time: '30 min + 1 hr rest',
    serves: 4,
    difficulty: 'Easy',
    intro: 'Soft, blistered and brushed with garlic butter — naan made in a normal frying pan. (In a hurry? Deep\'s frozen garlic naan is 3 minutes from freezer to table.)',
    ingredients: [
      { label: '1 tsp each: sugar, salt, baking powder & dried yeast', pantry: true },
      { label: 'Maida (plain flour, 3 cups)', products: ['pattu-maida'] },
      { label: 'Yoghurt (½ cup)', products: ['fresh-dahi'] },
      { label: 'Fresh garlic', products: ['garlic'] },
      { label: 'Butter or ghee, to brush', products: ['amul-butter', 'amul-ghee-500'] },
      { label: 'Shortcut: frozen garlic naan', products: ['deep-garlic-naan-4', 'deep-garlic-naan-12'] },
    ],
    steps: [
      'Mix flour, yeast, sugar, salt and baking powder. Add yoghurt and warm water to form a soft dough.',
      'Knead 5 minutes, then rest covered for 1 hour until puffy.',
      'Divide into 8 balls and roll into teardrops.',
      'Cook in a screaming-hot dry pan until bubbles char — about a minute per side.',
      'Brush immediately with melted butter mixed with grated garlic and coriander.',
      'Serve hot, stacked under a tea towel to stay soft.',
    ],
  },
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    emoji: '🥭',
    tagline: 'Five minutes, two ingredients, pure gold',
    time: '10 min',
    serves: 2,
    difficulty: 'Super easy',
    intro: 'The drink that cools every curry night. Creamy yoghurt, sweet Alphonso mango and a whisper of cardamom.',
    ingredients: [
      { label: '1 cup milk & ice cubes', pantry: true },
      { label: 'Yoghurt (1 cup)', products: ['fresh-dahi'] },
      { label: 'Alphonso mango pulp (or ripe mango)', products: ['deep-mango-pulp'] },
      { label: 'Green cardamom (a pinch, ground)', products: ['shudh-cardamom'] },
      { label: 'Sweet twist: a splash of Rooh Afza', products: ['rooh-afza'] },
    ],
    steps: [
      'Blend mango pulp, yoghurt, milk, a spoon of honey and cardamom until smooth.',
      'Pour over ice and top with a swirl of extra pulp.',
      'Serve immediately, ideally beside something spicy.',
    ],
  },
];
